server:
  internalPort: 2000
  externalPort: 2020
  #  runMode: release
  runMode: debug

logger:
  filePath: ../logs/
  encoding: json
  level: debug
  logger: zerolog

postgres:
  host: 185.215.244.211
  port: 5432
  user: postgresAdmin
  password: postgres1234quera$
  dbName: quera_telegram_bot
  sslMode: disable
  maxIdleConnections: 15
  maxOpenConnections: 100
  connectionMaxLifetime: 5

cors:
  allowOrigins: "*"

telegram:
  token: "7884113459:AAFt5uUWGalD4lpHZV7UDgCGlLVirUlbipc"
  adminPass: "amir.Delgarm@3041.quera"